package uz.gita.khasanboy_kitobim.ui.theme


import androidx.compose.ui.graphics.Color

val three_light_primary = Color(0xFF006972)
val three_light_onPrimary = Color(0xFFFFFFFF)
val three_light_primaryContainer = Color(0xFF8DF2FF)
val three_light_onPrimaryContainer = Color(0xFF001F23)
val three_light_secondary = Color(0xFF4A6366)
val three_light_onSecondary = Color(0xFFFFFFFF)
val three_light_secondaryContainer = Color(0xFFCDE7EB)
val three_light_onSecondaryContainer = Color(0xFF051F22)
val three_light_tertiary = Color(0xFF515E7D)
val three_light_onTertiary = Color(0xFFFFFFFF)
val three_light_tertiaryContainer = Color(0xFFD8E2FF)
val three_light_onTertiaryContainer = Color(0xFF0C1B36)
val three_light_error = Color(0xFFBA1A1A)
val three_light_errorContainer = Color(0xFFFFDAD6)
val three_light_onError = Color(0xFFFFFFFF)
val three_light_onErrorContainer = Color(0xFF410002)
val three_light_background = Color(0xFFFAFDFD)
val three_light_onBackground = Color(0xFF191C1D)
val three_light_surface = Color(0xFFFAFDFD)
val three_light_onSurface = Color(0xFF191C1D)
val three_light_surfaceVariant = Color(0xFFDAE4E6)
val three_light_onSurfaceVariant = Color(0xFF3F484A)
val three_light_outline = Color(0xFF6F797A)
val three_light_inverseOnSurface = Color(0xFFEFF1F1)
val three_light_inverseSurface = Color(0xFF2D3131)
val three_light_inversePrimary = Color(0xFF4ED8E8)
val three_light_shadow = Color(0xFF000000)
val three_light_surfaceTint = Color(0xFF006972)
val three_light_outlineVariant = Color(0xFFBEC8CA)
val three_light_scrim = Color(0xFF000000)

val three_dark_primary = Color(0xFF4ED8E8)
val three_dark_onPrimary = Color(0xFF00363C)
val three_dark_primaryContainer = Color(0xFF004F56)
val three_dark_onPrimaryContainer = Color(0xFF8DF2FF)
val three_dark_secondary = Color(0xFFB1CBCF)
val three_dark_onSecondary = Color(0xFF1C3437)
val three_dark_secondaryContainer = Color(0xFF324B4E)
val three_dark_onSecondaryContainer = Color(0xFFCDE7EB)
val three_dark_tertiary = Color(0xFFB9C6EA)
val three_dark_onTertiary = Color(0xFF23304D)
val three_dark_tertiaryContainer = Color(0xFF394664)
val three_dark_onTertiaryContainer = Color(0xFFD8E2FF)
val three_dark_error = Color(0xFFFFB4AB)
val three_dark_errorContainer = Color(0xFF93000A)
val three_dark_onError = Color(0xFF690005)
val three_dark_onErrorContainer = Color(0xFFFFDAD6)
val three_dark_background = Color(0xFF191C1D)
val three_dark_onBackground = Color(0xFFE0E3E3)
val three_dark_surface = Color(0xFF191C1D)
val three_dark_onSurface = Color(0xFFE0E3E3)
val three_dark_surfaceVariant = Color(0xFF3F484A)
val three_dark_onSurfaceVariant = Color(0xFFBEC8CA)
val three_dark_outline = Color(0xFF899294)
val three_dark_inverseOnSurface = Color(0xFF191C1D)
val three_dark_inverseSurface = Color(0xFFE0E3E3)
val three_dark_inversePrimary = Color(0xFF006972)
val three_dark_shadow = Color(0xFF000000)
val three_dark_surfaceTint = Color(0xFF4ED8E8)
val three_dark_outlineVariant = Color(0xFF3F484A)
val three_dark_scrim = Color(0xFF000000)


val three_seed = Color(0xFF0C5C64)
val ThreeSurfaceLight = Color(0x6EFAFDFD)
val ThreeSurfaceDark = Color(0x6E191C1D)
val ThreeSurface = if (Theme.isDarkMode.value) ThreeSurfaceDark else ThreeSurfaceLight

val ThreeSurfaceVariantLight = Color(0xFFDAE4E6)
val ThreeSurfaceVariantDark = Color(0xFF3F484A)
val ThreeSurfaceVariant = if (Theme.isDarkMode.value) ThreeSurfaceVariantDark else ThreeSurfaceVariantLight
